COLUMNS:
  Age: int32
  Gender: int32
  Family_Diabetes: int32
  highBP: int32
  PhysicallyActive: int32
  BMI: int32
  Smoking: int32
  Alcohol: int32
  Sleep: int32
  SoundSleep: int32
  RegularMedicine: int32
  JunkFood: int32
  Stress: int32
  BPLevel: int32
  Pregancies: int32
  Pdiabetes: int32
  UriationFreq: int32
  Diabetic: int32


TARGET_COLUMN:
  name: Diabetic