COLUMNS:
  Age: object
  Gender: object
  Family_Diabetes: object
  highBP: object
  PhysicallyActive: object
  BMI: float64
  Smoking: object
  Alcohol: object
  Sleep: int64
  SoundSleep: int64
  RegularMedicine: object
  JunkFood: object
  Stress: object
  BPLevel: object
  Pregancies: float64
  Pdiabetes: object
  UriationFreq: object
  Diabetic: object

TARGET_COLUMN:
  name: Diabetic