apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: NutBodyslam053/bd528:c595e37493560998de807b961399ec3f86620058
          ports:
          - containerPort: 8080
