artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/01_data_ingestion
  source_URL: https://github.com/NutBodyslam053/BD528-software_engineering/raw/main/data/diabetes_dataset__2019.zip
  local_data_file: artifacts/01_data_ingestion/data.zip
  unzip_dir: artifacts/01_data_ingestion