apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  # labels:
  #   app: github-runner
  name: github-runner
  namespace: github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner-container
        image: nutbodyslam053/github-runner:v1
        imagePullPolicy: Always
        env:
        - name: GITHUB_TOKEN 
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_TOKEN
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_USER
        - name: GITHUB_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_REPOSITORY
        # resources: 
        #   requests: 
        #     cpu: 20m 
        #     memory: 512Mi 
status: {}
