apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: github-runner
  name: github-runner
  namespace: github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner-container
        image: nutbodyslam053/github-runner:v2
        imagePullPolicy: Always
        env:
        - name: GITHUB_TOKEN 
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_TOKEN
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_USER
        - name: GITHUB_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_REPOSITORY
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - name: data
          mountPath: /_work

      - name: dind-container
        image: docker:24.0.7-dind
        imagePullPolicy: Always
        securityContext: 
          privileged: true 
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        resources: 
          requests: 
            cpu: 20m 
            memory: 512Mi 
        volumeMounts: 
        - name: dind-storage 
          mountPath: /var/lib/docker 
        - name: data
          mountPath: /_work

      volumes:
      - name: dind-storage 
        emptyDir: {}
      - name: data
        emptyDir: {}

status: {}
