apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: nutbodyslam053
type: Opaque
data:
  GITHUB_TOKEN: Z2hwXzNlNTBVOW9ZQ1lGNTV0c2RCUmFCTWNBWmRSY3NBOTJ0NmZBSg==
  GITHUB_USER: bnV0Ym9keXNsYW0wNTM=
  GITHUB_REPOSITORY: QkQ1Mjgtc29mdHdhcmVfZW5naW5lZXJpbmc=
